[workspace]
authors = ["Luan Leal <luanleal@usp.br>"]
channels = ["conda-forge", "bioconda"]
name = "PlasmidEvo"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
python = ">=3.12.12,<3.13"
seqkit = ">=2.12.0,<3"
biopython = ">=1.86,<2"
memory_profiler = ">=0.61.0,<0.62"
jupyterlab = ">=4.5.2,<5"
needletail = ">=0.7.1,<0.8"
pyrodigal = ">=3.7.0,<4"
click = ">=8.3.1,<9"
diamond = ">=2.1.18,<3"
polars = ">=1.37.1,<2"
matplotlib = ">=3.10.8,<4"
python-lsp-server = ">=1.14.0,<2"
igraph = ">=1.0.1,<2"
python-igraph = ">=1.0.0,<2"
pycairo = ">=1.29.0,<2"
leidenalg = ">=0.11.0,<0.12"
jupyter_console = ">=6.6.3,<7"
infomap = ">=2.8.0,<3"
graph-tool = ">=2.98,<3"
ijson = ">=3.4.0.post0,<4"
bakta = ">=1.8.1,<2"
jupyterlab_vim = ">=4.1.4,<5"
seaborn = ">=0.13.2,<0.14"
mob_suite = ">=3.0.0,<4"
numpy = ">=2.4.1,<3"
duckdb = ">=1.4.4,<2"
tqdm = ">=4.67.3,<5"

[tasks]
build = "pip install -e ."

[pypi-dependencies]
pygraphina = ">=0.2.2, <0.3"
